#!/usr/bin/env bash

set -euxo pipefail
DEST="/home/ubuntu/.cache/hackage"

command mkdir -p $DEST || true
command mkdir -p docs || true
command cp -a $(stack path --local-doc-root)/unagi-conduit-1.0.0.0/* -- "$DEST/"
command cp -a $(stack path --local-doc-root)/unagi-conduit-1.0.0.0/* -- "docs/"

command git config --global user.name "CircleCI docs update"
command git config --global user.email "ci@circleci.com"
command git fetch --all
command git reset --soft master

# if the upstream has changed because of concurrent builds, just give
# up
command git add docs
command git commit -m "[automated] [ci skip] write-docs: updated haddock" || true
command git remote add authorized "https://$GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git"
command git push authorized master:master || true
